---
- name: Setup Linux development environment for Rust and Substrate
  hosts: all

  tasks:
    # Install essential packages (requires sudo)
    - name: Install required packages
      become: yes
      apt:
        name:
          - build-essential
          - clang
          - curl
          - git
          - libssl-dev
          - protobuf-compiler
        state: present

    # Install Rust
    - name: Install Rust
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    # Source cargo env
    - name: Source cargo env
      shell: source $HOME/.cargo/env
      args:
        executable: /bin/bash

    # Verify Rust installation
    - name: Verify Rust installation
      shell: rustc --version
      register: rustc_output
      ignore_errors: true

    - name: Show rustc version
      debug:
        var: rustc_output.stdout_lines

    # Configure Rust toolchain
    - name: Set default toolchain to stable
      shell: rustup default stable

    - name: Update Rust
      shell: rustup update

    # Add nightly toolchain and wasm target
    - name: Add nightly toolchain
      shell: rustup update nightly

    - name: Add wasm target
      shell: rustup target add wasm32-unknown-unknown --toolchain nightly
