---
- name: Setup Linux development environment for Rust and Substrate
  hosts: all

  tasks:
    # Install essential packages (requires sudo)
    - name: Install required packages
      become: yes
      apt:
        name:
          - build-essential
          - clang
          - curl
          - git
          - libssl-dev
          - protobuf-compiler
        state: present

    # Install Rust
    - name: Install Rust
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    # Source cargo env
    - name: Source cargo env
      shell: echo 'source $HOME/.cargo/env' >> $HOME/.bashrc

    # Verify Rust installation
    - name: Verify Rust installation
      shell: source $HOME/.cargo/env && rustc --version
      register: rustc_output
      args:
        executable: /bin/bash

    - name: Show rustc version
      debug:
        var: rustc_output.stdout_lines

    # Configure Rust toolchain
    - name: Set default toolchain to stable
      shell: source $HOME/.cargo/env && rustup default stable
      args:
        executable: /bin/bash

    - name: Update Rust
      shell: source $HOME/.cargo/env && rustup update
      args:
        executable: /bin/bash

    # Add nightly toolchain and wasm target
    - name: Add nightly toolchain
      shell: source $HOME/.cargo/env && rustup update nightly
      args:
        executable: /bin/bash

    - name: Add wasm target
      shell: source $HOME/.cargo/env && rustup target add wasm32-unknown-unknown --toolchain nightly
      args:
        executable: /bin/bash
